/* KeySuite V4.23.11 — BFI global integration (Product, Selection, Price List, Quote, Assembly). */
(()=>{'use strict';
if(window.__KEYSUITE_BFI_V42302__)return;window.__KEYSUITE_BFI_V42302__=true;
const $=id=>document.getElementById(id),DB=()=>window.KeySuiteBFIProductData||{models:[]},esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=(v,d=2)=>Number(v||0).toLocaleString('en-MY',{minimumFractionDigits:d,maximumFractionDigits:d});
let data=null,access=null,selectedSeries='ALL',brandContext={name:'B.G.Reich',brandSeries:'BFI',sellingSeries:'BFI'};
function rows(){return (data?.bfiProducts?.length?data.bfiProducts:DB().models||[]).slice()}
function brandName(){return brandContext.name||'B.G.Reich'}
function baseModelName(model){return String(model||'').trim().replace(/[TE]$/i,'')}
function motorEffForPhase(phase){return String(phase||'3Ph')==='1Ph'?'IE1':'IE2'}
function displayModel(model,phase=''){const phased=String(phase||'')==='3Ph'?baseModelName(model)+'T':baseModelName(model),selling=String(brandContext.sellingSeries||brandContext.brandSeries||'BFI').trim();return selling&&selling.toUpperCase()!=='BFI'?phased.replace(/^BFI\b/i,selling):phased}
function phaseFor(product,requested='3Ph'){const phases=product?.phases||['1Ph','3Ph'];return phases.includes(requested)?requested:(phases.includes('3Ph')?'3Ph':phases[0])}
function quoteDescription(product,phase,options={}){const seal=options.seal||'Car/Cer',elastomer=options.elastomer||'Viton',modelLabel=options.modelLabel||displayModel(product.model,phase),imp=product.smallImpellers?`${product.fullImpellers} full + ${product.smallImpellers} reduced`:`${product.totalImpellers||product.stages}`;return [`${brandName()} BFI Horizontal Multistage Pump Model: ${modelLabel}`,`Motor: ${num(product.motor_kw,2)} kW / ${num(product.motor_hp,2)} HP · 2 Pole · ${motorEffForPhase(phase)} · ${phase} · 50 Hz`,`Suction & Discharge: ${product.inlet} x ${product.outlet}`,`Impellers: ${imp}`,`Mechanical Seal: ${seal}`,`Elastomer: ${elastomer}`,`Maximum Operating Pressure: ${num(product.max_pressure_bar,1)} bar`].join('\n')}
function currentOptions(){return {phase:$('bfiProductPhase')?.value||'3Ph',seal:$('bfiProductSeal')?.value||'Car/Cer',elastomer:$('bfiProductElastomer')?.value||'Viton'}}
function find(model){const wanted=baseModelName(model).toLowerCase();return rows().find(r=>String(r.model).toLowerCase()===wanted||String(r.id)===String(model||''))||null}
function pricing(model,phase,mode='quotation'){return window.KeySuitePricing?.findBfiPrice?.(model,phase,{pricingMode:mode})||null}
function routeSelection(payload,route='quotation'){
  const product=find(payload?.model||payload?.base_model);if(!product){alert('BFI model could not be found.');return false}
  const phase=phaseFor(product,payload?.motor_phase||payload?.phase||'3Ph'),seal=payload?.keysuite_seal||'Car/Cer',elastomer=payload?.keysuite_elastomer||'Viton',enhanced=phase==='3Ph'&&(/E$/i.test(String(payload?.model||payload?.display_model||payload?.quotation_model||''))||payload?.enhanced===true||payload?.enhanced_curve===true);
  if(!window.KeySuiteApp?.ensureQuotationPricingContext?.(`add a BFI pump to the ${route==='assembly'?'Assembly':'quotation'}`))return false;
  const priceIdentity=phase==='3Ph'?`${baseModelName(product.model)}${enhanced?'E':'T'}`:baseModelName(product.model),quoteModel=enhanced?`${baseModelName(product.model)}E`:displayModel(product.model,phase),found=pricing(priceIdentity,phase,route==='assembly'?'assembly':'quotation');
  if(!found){const reason=window.KeySuitePricing?.bfiPriceProblem?.(priceIdentity,phase,{pricingMode:route==='assembly'?'assembly':'quotation'})||`BFI pricing is unavailable for ${quoteModel}.`;alert(reason);return false}
  if(route!=='assembly'&&!window.KeySuitePricing?.ensureQuoteableCalculation?.(found.calc,quoteModel))return false;
  const source=window.KeySuitePricing.sourceSnapshot(found),item={model:quoteModel,description:quoteDescription(product,phase,{seal,elastomer,modelLabel:quoteModel}),qty:1,unitPrice:found.calc.finalPrice,pricingSource:{...source,motor_phase:phase,seal_faces:seal,seal_elastomer:elastomer},productFamily:'BFI',pumpData:{...payload,model:product.model,quotation_model:quoteModel,display_model:quoteModel,motor_efficiency_class:motorEffForPhase(phase),keysuite_product_family:'BFI',keysuite_brand_name:brandName(),enhanced},assemblyLevel:'PUMPSET_COMPONENT',assemblySection:'pump'};
  if(route==='assembly'){window.KeySuiteAssembly?.addItem?.(item);window.KeySuiteApp?.showPage?.('assembly');return true}
  const row=window.KeySuiteApp?.addExternalQuoteItem?.(item);if(row)window.KeySuiteApp?.showPage?.('quotation');return !!row;
}
function openCurve(model){const product=find(model);if(!product)return false;const runtime=window.KeySuiteV394411ProductCurve||window.KeySuiteV394410ProductCurve||window.KeySuiteV39449ProductCurve||window.KeySuiteV39448ProductCurve;try{if(runtime&&typeof runtime.open==='function'&&runtime.open('BFI',product.model,'BFI')!==false)return true}catch(error){console.warn('Shared BFI Product curve route failed.',error)}return false}
function renderProduct(){const seriesHost=$('bfiProductSeriesList'),grid=$('bfiProductModelGrid'),count=$('bfiProductModelCount');if(!seriesHost||!grid)return;const all=rows(),series=[...new Set(all.map(r=>r.series))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));seriesHost.innerHTML='';['ALL',...series].forEach(s=>{const b=document.createElement('button');b.type='button';b.className='product-series-button'+(selectedSeries===s?' active':'');b.textContent=s==='ALL'?'All BFI':s;b.onclick=()=>{selectedSeries=s;renderProduct()};seriesHost.appendChild(b)});const search=String($('bfiProductSearch')?.value||'').trim().toLowerCase(),phase=$('bfiProductPhase')?.value||'3Ph';const filtered=all.filter(r=>{const ph=phaseFor(r,phase);return (selectedSeries==='ALL'||r.series===selectedSeries)&&(!search||String(r.model).toLowerCase().includes(search)||displayModel(r.model,ph).toLowerCase().includes(search))});if(count)count.textContent=`${filtered.length} model${filtered.length===1?'':'s'}`;grid.innerHTML='';filtered.forEach(p=>{const ph=phaseFor(p,phase),row=document.createElement('div');row.className='product-model-row';row.innerHTML=`<h3>${esc(displayModel(p.model,ph))}</h3><div class="product-model-actions"><button class="btn secondary product-action-button" type="button" data-bfi-curve data-bfi-model="${esc(p.model)}">Curve</button><button class="btn action-assembly product-action-button" type="button" data-bfi-assembly>Assembly</button><button class="btn action-quote product-action-button" type="button" data-bfi-quote>Quote</button></div>`;row.querySelector('[data-bfi-curve]').onclick=()=>openCurve(p.model);row.querySelector('[data-bfi-assembly]').onclick=()=>routeSelection({model:p.model,motor_phase:ph,keysuite_seal:$('bfiProductSeal')?.value,keysuite_elastomer:$('bfiProductElastomer')?.value},'assembly');row.querySelector('[data-bfi-quote]').onclick=()=>routeSelection({model:p.model,motor_phase:ph,keysuite_seal:$('bfiProductSeal')?.value,keysuite_elastomer:$('bfiProductElastomer')?.value},'quotation');grid.appendChild(row)})}
function priceCell(p,currency,phase){const v=p.pricesByCurrency?.[currency]?.[phase];return Number.isFinite(Number(v))?Number(v):0}
function rarityCell(p,currency,phase){return String(p.rarityByCurrency?.[currency]?.[phase]||'common').toLowerCase()}
function renderPriceList(){const body=$('bfiPriceRows');if(!body)return;const currency=$('bfiPriceCurrency')?.value||'MYR',search=String($('bfiPriceSearch')?.value||'').trim().toLowerCase(),list=rows().filter(p=>!search||String(p.model).toLowerCase().includes(search));$('bfiPriceListCount').textContent=`${list.length} models · ${currency}`;body.innerHTML='';for(const p of list){const tr=document.createElement('tr');const phaseHtml=ph=>(p.phases||[]).includes(ph)?`<div class="bfi-price-pair"><input type="number" min="0" step="0.01" data-bfi-price="${ph}" value="${priceCell(p,currency,ph)}"><select data-bfi-rarity="${ph}"><option value="many">Many</option><option value="common">Common</option><option value="rare">Rare</option><option value="fixed">Fixed</option></select></div>`:'<span class="muted">N/A</span>';tr.innerHTML=`<td><b>${esc(p.model)}</b></td><td>${phaseHtml('1Ph')}</td><td>${phaseHtml('3Ph')}</td><td><button class="btn" data-bfi-save>Save</button></td>`;for(const ph of ['1Ph','3Ph']){const sel=tr.querySelector(`[data-bfi-rarity="${ph}"]`);if(sel)sel.value=rarityCell(p,currency,ph)}tr.querySelector('[data-bfi-save]').onclick=()=>savePriceRow(p,tr,currency);body.appendChild(tr)}window.dispatchEvent(new Event('keysuite-price-list-rendered'))}
async function savePriceRow(p,tr,currency){const client=window.KeySuiteAuth?.getClient?.();if(!client)return;const get=(attr,ph)=>tr.querySelector(`[${attr}="${ph}"]`),v1=get('data-bfi-price','1Ph'),v3=get('data-bfi-price','3Ph'),r1=get('data-bfi-rarity','1Ph'),r3=get('data-bfi-rarity','3Ph'),button=tr.querySelector('[data-bfi-save]');button.disabled=true;button.textContent='Saving…';try{const {error}=await client.rpc('keysuite_save_bfi_product_price_v42302',{p_product_id:p.id,p_currency:currency,p_price_1ph:v1?Number(v1.value||0):null,p_price_3ph:v3?Number(v3.value||0):null,p_rarity_1ph:r1?.value||'common',p_rarity_3ph:r3?.value||'common'});if(error)throw error;for(const [ph,input,sel] of [['1Ph',v1,r1],['3Ph',v3,r3]])if(input){p.pricesByCurrency[currency][ph]=Number(input.value||0);p.rarityByCurrency[currency][ph]=sel.value}button.textContent='Saved';setTimeout(()=>button.textContent='Save',900);window.KeySuitePricing?.syncPriceListSettings?.({bfiProducts:rows()})}catch(e){console.error(e);alert(`BFI price could not be saved: ${e.message||e}`);button.textContent='Save'}finally{button.disabled=false}}
async function saveRate(currency){const id=currency==='USD'?'bfiUsdMultiplier':'bfiRmbMultiplier',input=$(id),client=window.KeySuiteAuth?.getClient?.(),value=Number(input?.value);if(!client||!(value>0))return;const {error}=await client.rpc('keysuite_save_bfi_multiplier_v42302',{p_currency:currency,p_multiplier:value});if(error){alert(`BFI multiplier could not be saved: ${error.message||error}`);return}data.productMultipliers.BFI={...(data.productMultipliers.BFI||{}),[currency]:value,MYR:1};window.KeySuitePricing?.syncPriceListSettings?.({productMultipliers:data.productMultipliers});}
function init(next,userAccess){data=next||data||{};access=userAccess||access;if(data?.productMultipliers?.BFI){if($('bfiUsdMultiplier'))$('bfiUsdMultiplier').value=data.productMultipliers.BFI.USD||1;if($('bfiRmbMultiplier'))$('bfiRmbMultiplier').value=data.productMultipliers.BFI.RMB||1}renderProduct();renderPriceList()}
function bind(){if(document.body.dataset.bfi42302Bound)return;document.body.dataset.bfi42302Bound='1';$('bfiProductSearch')?.addEventListener('input',renderProduct);$('bfiProductPhase')?.addEventListener('change',renderProduct);$('bfiPriceSearch')?.addEventListener('input',renderPriceList);$('bfiPriceCurrency')?.addEventListener('change',renderPriceList);$('saveBfiUsdMultiplier')?.addEventListener('click',()=>saveRate('USD'));$('saveBfiRmbMultiplier')?.addEventListener('click',()=>saveRate('RMB'));window.addEventListener('KEYSUITE_V393_BRAND_CONTEXT_CHANGED',ev=>{if(String(ev.detail?.family||'').toUpperCase()!=='BFI')return;brandContext={...brandContext,...ev.detail};renderProduct()});window.addEventListener('message',ev=>{const m=ev.data||{};if(m.type==='KEYSUITE_PRODUCT_FRAME_READY'&&String(m.family||'').toUpperCase()==='BFI'){$('productBfiSelectorFrame')?.contentWindow?.postMessage({type:'KEYSUITE_V393_BRAND_CONTEXT',brand:brandContext},'*')}})}
function pageShown(id){if(id==='productBfi')renderProduct();if(id==='bfiPriceList')renderPriceList()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{bind();data=window.KEYSUITE_SECURE_DATA||data;renderProduct();renderPriceList()},{once:true});else{bind();data=window.KEYSUITE_SECURE_DATA||data;renderProduct();renderPriceList()}
window.KeySuiteBFI={version:'4.23.11',init,rows,find,renderProduct,renderPriceList,pageShown,openCurve,routeSelection,quoteDescription};
})();
