/* KeySuite V4.23.03 — BFI global integration (Product, Selection, Price List, Quote, Assembly). */
(()=>{'use strict';
if(window.__KEYSUITE_BFI_V42302__)return;window.__KEYSUITE_BFI_V42302__=true;
const $=id=>document.getElementById(id),DB=()=>window.KeySuiteBFIProductData||{models:[]},esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),num=(v,d=2)=>Number(v||0).toLocaleString('en-MY',{minimumFractionDigits:d,maximumFractionDigits:d});
let data=null,access=null,selectedSeries='ALL',brandContext={name:'B.G.Reich',brandSeries:'BFI',sellingSeries:'BFI'};
function rows(){return (data?.bfiProducts?.length?data.bfiProducts:DB().models||[]).slice()}
function brandName(){return brandContext.name||'B.G.Reich'}
function displayModel(model){const selling=String(brandContext.sellingSeries||brandContext.brandSeries||'BFI').trim();return selling&&selling.toUpperCase()!=='BFI'?String(model||'').replace(/^BFI\b/i,selling):String(model||'')}
function phaseFor(product,requested='3Ph'){const phases=product?.phases||['1Ph','3Ph'];return phases.includes(requested)?requested:(phases.includes('3Ph')?'3Ph':phases[0])}
function quoteDescription(product,phase,options={}){const seal=options.seal||'Car/Cer',elastomer=options.elastomer||'Viton',imp=product.smallImpellers?`${product.fullImpellers} full + ${product.smallImpellers} reduced`:`${product.totalImpellers||product.stages}`;return [`${brandName()} BFI Horizontal Multistage Pump Model: ${displayModel(product.model)}`,`Motor: ${num(product.motor_kw,2)} kW / ${num(product.motor_hp,2)} HP · 2 Pole · IE3 · ${phase} · 50 Hz`,`Suction & Discharge: ${product.inlet} x ${product.outlet}`,`Impellers: ${imp}`,`Mechanical Seal: ${seal}`,`Elastomer: ${elastomer}`,`Maximum Operating Pressure: ${num(product.max_pressure_bar,1)} bar`].join('\n')}
function currentOptions(){return {phase:$('bfiProductPhase')?.value||'3Ph',seal:$('bfiProductSeal')?.value||'Car/Cer',elastomer:$('bfiProductElastomer')?.value||'Viton'}}
function find(model){return rows().find(r=>String(r.model).toLowerCase()===String(model||'').toLowerCase()||String(r.id)===String(model||''))||null}
function pricing(model,phase,mode='quotation'){return window.KeySuitePricing?.findBfiPrice?.(model,phase,{pricingMode:mode})||null}
function routeSelection(payload,route='quotation'){
  const product=find(payload?.model||payload?.base_model);if(!product){alert('BFI model could not be found.');return false}
  const phase=phaseFor(product,payload?.motor_phase||payload?.phase||'3Ph'),seal=payload?.keysuite_seal||'Car/Cer',elastomer=payload?.keysuite_elastomer||'Viton';
  if(!window.KeySuiteApp?.ensureQuotationPricingContext?.(`add a BFI pump to the ${route==='assembly'?'Assembly':'quotation'}`))return false;
  const found=pricing(product.model,phase,route==='assembly'?'assembly':'quotation');
  if(!found){alert(`No BFI source price is available for ${product.model} (${phase}). The supplied V1.0 BFI pricelist starts at 0.00; enter a source price in Key → Price List → BFI first.`);return false}
  if(route!=='assembly'&&!window.KeySuitePricing?.ensureQuoteableCalculation?.(found.calc,product.model))return false;
  const source=window.KeySuitePricing.sourceSnapshot(found),item={model:displayModel(product.model),description:quoteDescription(product,phase,{seal,elastomer}),qty:1,unitPrice:found.calc.finalPrice,pricingSource:{...source,motor_phase:phase,seal_faces:seal,seal_elastomer:elastomer},productFamily:'BFI',pumpData:{...payload,model:product.model,quotation_model:displayModel(product.model),keysuite_product_family:'BFI',keysuite_brand_name:brandName()},assemblyLevel:'PUMPSET_COMPONENT',assemblySection:'pump'};
  if(route==='assembly'){window.KeySuiteAssembly?.addItem?.(item);window.KeySuiteApp?.showPage?.('assembly');return true}
  const row=window.KeySuiteApp?.addExternalQuoteItem?.(item);if(row)window.KeySuiteApp?.showPage?.('quotation');return !!row;
}
function openCurve(model){const product=find(model);if(!product)return;const dialog=$('bfiCurveDialog'),host=$('bfiCurveHost'),frame=$('productBfiSelectorFrame');if(!dialog||!host||!frame)return;const src=frame.dataset.src||'selector-bfi/product.html?product=1&v=42303';if(frame.getAttribute('src')==='about:blank')frame.src=src;frame.style.display='block';frame.style.width='100%';frame.style.height='1680px';frame.style.border='0';host.innerHTML='';host.appendChild(frame);const title=$('bfiCurveTitle');if(title)title.textContent=`${brandName()} · ${displayModel(product.model)} Curve`;dialog.showModal?.();const send=()=>{try{frame.contentWindow?.postMessage({type:'KEYSUITE_V393_BRAND_CONTEXT',brand:brandContext},'*');frame.contentWindow?.postMessage({type:'KEYSUITE_PRODUCT_MODEL',model:product.model,family:'BFI'},'*')}catch(_){}};frame.addEventListener('load',send,{once:true});setTimeout(send,120)}
function renderProduct(){const seriesHost=$('bfiProductSeriesList'),grid=$('bfiProductModelGrid'),count=$('bfiProductModelCount');if(!seriesHost||!grid)return;const all=rows(),series=[...new Set(all.map(r=>r.series))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));seriesHost.innerHTML='';['ALL',...series].forEach(s=>{const b=document.createElement('button');b.type='button';b.className='product-series-button'+(selectedSeries===s?' active':'');b.textContent=s==='ALL'?'All BFI':s;b.onclick=()=>{selectedSeries=s;renderProduct()};seriesHost.appendChild(b)});const search=String($('bfiProductSearch')?.value||'').trim().toLowerCase(),phase=$('bfiProductPhase')?.value||'3Ph';const filtered=all.filter(r=>(selectedSeries==='ALL'||r.series===selectedSeries)&&(!search||String(r.model).toLowerCase().includes(search)));if(count)count.textContent=`${filtered.length} model${filtered.length===1?'':'s'}`;grid.innerHTML='';filtered.forEach(p=>{const ph=phaseFor(p,phase),card=document.createElement('div');card.className='product-model-card';card.innerHTML=`<div class="product-model-card-head"><b>${esc(displayModel(p.model))}</b><span>${esc(p.series)}</span></div><div class="muted">${num(p.motor_kw,2)} kW · ${num(p.motor_hp,2)} HP · ${esc(p.connection)} · ${esc((p.phases||[]).join(' / '))}</div><div class="actions" style="margin-top:10px"><button class="btn secondary" data-bfi-curve>Curve</button><button class="btn action-assembly" data-bfi-assembly>Assembly</button><button class="btn action-quote" data-bfi-quote>Quote</button></div>`;card.querySelector('[data-bfi-curve]').onclick=()=>openCurve(p.model);card.querySelector('[data-bfi-assembly]').onclick=()=>routeSelection({model:p.model,motor_phase:ph,keysuite_seal:$('bfiProductSeal')?.value,keysuite_elastomer:$('bfiProductElastomer')?.value},'assembly');card.querySelector('[data-bfi-quote]').onclick=()=>routeSelection({model:p.model,motor_phase:ph,keysuite_seal:$('bfiProductSeal')?.value,keysuite_elastomer:$('bfiProductElastomer')?.value},'quotation');grid.appendChild(card)})}
function priceCell(p,currency,phase){const v=p.pricesByCurrency?.[currency]?.[phase];return Number.isFinite(Number(v))?Number(v):0}
function rarityCell(p,currency,phase){return String(p.rarityByCurrency?.[currency]?.[phase]||'common').toLowerCase()}
function renderPriceList(){const body=$('bfiPriceRows');if(!body)return;const currency=$('bfiPriceCurrency')?.value||'MYR',search=String($('bfiPriceSearch')?.value||'').trim().toLowerCase(),list=rows().filter(p=>!search||String(p.model).toLowerCase().includes(search));$('bfiPriceListCount').textContent=`${list.length} models · ${currency}`;body.innerHTML='';for(const p of list){const tr=document.createElement('tr');const phaseHtml=ph=>(p.phases||[]).includes(ph)?`<div class="bfi-price-pair"><input type="number" min="0" step="0.01" data-bfi-price="${ph}" value="${priceCell(p,currency,ph)}"><select data-bfi-rarity="${ph}"><option value="many">Many</option><option value="common">Common</option><option value="rare">Rare</option><option value="fixed">Fixed</option></select></div>`:'<span class="muted">N/A</span>';tr.innerHTML=`<td><b>${esc(p.model)}</b></td><td>${phaseHtml('1Ph')}</td><td>${phaseHtml('3Ph')}</td><td><button class="btn" data-bfi-save>Save</button></td>`;for(const ph of ['1Ph','3Ph']){const sel=tr.querySelector(`[data-bfi-rarity="${ph}"]`);if(sel)sel.value=rarityCell(p,currency,ph)}tr.querySelector('[data-bfi-save]').onclick=()=>savePriceRow(p,tr,currency);body.appendChild(tr)}window.dispatchEvent(new Event('keysuite-price-list-rendered'))}
async function savePriceRow(p,tr,currency){const client=window.KeySuiteAuth?.getClient?.();if(!client)return;const get=(attr,ph)=>tr.querySelector(`[${attr}="${ph}"]`),v1=get('data-bfi-price','1Ph'),v3=get('data-bfi-price','3Ph'),r1=get('data-bfi-rarity','1Ph'),r3=get('data-bfi-rarity','3Ph'),button=tr.querySelector('[data-bfi-save]');button.disabled=true;button.textContent='Saving…';try{const {error}=await client.rpc('keysuite_save_bfi_product_price_v42302',{p_product_id:p.id,p_currency:currency,p_price_1ph:v1?Number(v1.value||0):null,p_price_3ph:v3?Number(v3.value||0):null,p_rarity_1ph:r1?.value||'common',p_rarity_3ph:r3?.value||'common'});if(error)throw error;for(const [ph,input,sel] of [['1Ph',v1,r1],['3Ph',v3,r3]])if(input){p.pricesByCurrency[currency][ph]=Number(input.value||0);p.rarityByCurrency[currency][ph]=sel.value}button.textContent='Saved';setTimeout(()=>button.textContent='Save',900);window.KeySuitePricing?.syncPriceListSettings?.({bfiProducts:rows()})}catch(e){console.error(e);alert(`BFI price could not be saved: ${e.message||e}`);button.textContent='Save'}finally{button.disabled=false}}
async function saveRate(currency){const id=currency==='USD'?'bfiUsdMultiplier':'bfiRmbMultiplier',input=$(id),client=window.KeySuiteAuth?.getClient?.(),value=Number(input?.value);if(!client||!(value>0))return;const {error}=await client.rpc('keysuite_save_bfi_multiplier_v42302',{p_currency:currency,p_multiplier:value});if(error){alert(`BFI multiplier could not be saved: ${error.message||error}`);return}data.productMultipliers.BFI={...(data.productMultipliers.BFI||{}),[currency]:value,MYR:1};window.KeySuitePricing?.syncPriceListSettings?.({productMultipliers:data.productMultipliers});}
function init(next,userAccess){data=next||data||{};access=userAccess||access;if(data?.productMultipliers?.BFI){if($('bfiUsdMultiplier'))$('bfiUsdMultiplier').value=data.productMultipliers.BFI.USD||1;if($('bfiRmbMultiplier'))$('bfiRmbMultiplier').value=data.productMultipliers.BFI.RMB||1}renderProduct();renderPriceList()}
function bind(){if(document.body.dataset.bfi42302Bound)return;document.body.dataset.bfi42302Bound='1';$('bfiProductSearch')?.addEventListener('input',renderProduct);$('bfiProductPhase')?.addEventListener('change',renderProduct);$('bfiPriceSearch')?.addEventListener('input',renderPriceList);$('bfiPriceCurrency')?.addEventListener('change',renderPriceList);$('saveBfiUsdMultiplier')?.addEventListener('click',()=>saveRate('USD'));$('saveBfiRmbMultiplier')?.addEventListener('click',()=>saveRate('RMB'));window.addEventListener('KEYSUITE_V393_BRAND_CONTEXT_CHANGED',ev=>{if(String(ev.detail?.family||'').toUpperCase()!=='BFI')return;brandContext={...brandContext,...ev.detail};renderProduct()});window.addEventListener('message',ev=>{const m=ev.data||{};if(m.type==='KEYSUITE_PRODUCT_FRAME_READY'&&String(m.family||'').toUpperCase()==='BFI'){$('productBfiSelectorFrame')?.contentWindow?.postMessage({type:'KEYSUITE_V393_BRAND_CONTEXT',brand:brandContext},'*')}})}
function pageShown(id){if(id==='productBfi')renderProduct();if(id==='bfiPriceList')renderPriceList()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{bind();data=window.KEYSUITE_SECURE_DATA||data;renderProduct();renderPriceList()},{once:true});else{bind();data=window.KEYSUITE_SECURE_DATA||data;renderProduct();renderPriceList()}
window.KeySuiteBFI={version:'4.23.03',init,rows,find,renderProduct,renderPriceList,pageShown,openCurve,routeSelection,quoteDescription};
})();
